### ISSUE TITLE
Rewrite the script with pandas

### ISSUE THREAD

**Issue by stdombek** [stdombek/folio_reporting_project_extracted_derived_tables#2]
In addition to the output as an HTML file, there should also be a way to generate Markdown files.

**Comment by amzoss** [comment]
If the script were using the [pandas](https://pandas.pydata.org/docs/index.html) package to do some of the data manipulation, I think that package has the ability to print a data frame as Markdown:

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_markdown.html

Pandas might make some of the other parts of the script easier, too - perhaps the query results and manual CSV could be loaded as data frames and then joined together, more like a database.

I was hoping to test the script more myself before our meeting, but I ran out of time. I'm sorry! Thanks so much for all of your work so far!

**Comment by amzoss** [comment]
There is a sample approach in [this amzoss branch](https://github.com/amzoss/folio_reporting_project_extracted_derived_tables/tree/fix-pandas-join) that I believe now gives the correct match between attribute data from the database and manual CSV records from a GitHub repository.

**Comment by stdombek** [comment]
Hi @amzoss , the output looks very good. The next steps could be done differently. 

- 1st variant: You can create a PR and we provide your script on GitHub in this repository.
- 2nd variant: I create the modularization of the script at first and after that we load your part as a function in the script. Unfortunately, the modularization takes a little time. I think that will last until mid-March.

**Comment by stdombek** [comment]
Issue can closed. I uploaded a variant https://github.com/stdombek/folio_reporting_project_extracted_derived_tables/blob/main/python/data_pipeline_sec_pandas.py . In the next step I will do the modularization.
